### ISSUE TITLE
vue/no-deprecated-slot-attribute

### ISSUE THREAD

**Issue by peterennis** [ionic-team/tutorial-photo-gallery-vue#2]
VS Code
Install recommended extension (Vetur)
Shows error on slot
Deprecated in Vue but still used in Ionic

![2020-10-03 20_27_42-Window](https://user-images.githubusercontent.com/140737/95006283-bf34e180-05b7-11eb-9216-09d4d6251f90.png)

![2020-10-03 20_29_32-Window](https://user-images.githubusercontent.com/140737/95006284-c6f48600-05b7-11eb-9379-3b46fb903d42.png)

**Comment by dotNetkow** [comment]
I'm using Vetur too! Great extension. I'm surprised that syntax highlighting isn't natively included in VS Code...

Anyway, this is expected. I'm not a Vue expert, but it's my understanding that Vue 2 templates had a "slot" attribute. They are deprecated in Vue 3, hence the warning. However, "slot" is a valid web component attribute, and since Ionic 4+ is built on web components, this warning is triggered. So, Vetur is right, but it's also wrong.  :)

You can safely ignore it. If it bothers you, try turning off "Vetur > Validation: Template." Cheers!
